Task 3
toxakaz/formal-language-course pull request #3
Opened 2022-09-25 15:29 UTC by toxakaz

task_3 ready for check

2022-09-25 15:30 UTC, toxakaz commented
В ближайшее время добавлю ещё тестов для поиска пути в графе.

2022-09-27 13:34 UTC, rustam-azimov requested changes

2022-09-27 13:34 UTC, rustam-azimov commented on project/boolean_matrices.py
> +
__all__ добавить

2022-09-27 13:34 UTC, rustam-azimov commented on project/boolean_matrices.py
> +nfa_as_matrix = namedtuple(
Ну чтобы такое не делать, лучше бы конечно было класс создать BoolDecomposedNFA который может строится по автомату. И у него методы from/to nfa, intersect с другим таким объектом, и get_reachable

2022-09-27 13:34 UTC, rustam-azimov commented on project/boolean_matrices.py
> +def cross_boolean_matrices(
intersect_nfa

2022-09-27 13:34 UTC, rustam-azimov commented on project/boolean_matrices.py
> +from scipy.sparse import dok_matrix
import scipy

2022-09-27 13:34 UTC, rustam-azimov commented on project/graph_find_path.py
> +def graph_find_path(
regular_path_querying

2022-09-28 15:10 UTC, rustam-azimov approved these changes

2022-09-28 15:44 UTC, merged